"""Manager/Analytics Orchestrator Bot (Bot 8)."""
from __future__ import annotations

import json
import logging
from datetime import datetime, timezone
from pathlib import Path

from bots.base import BaseBot
from bots.orchestrator.models import (
    ActionableTask,
    BotSummary,
    OrchestratorInput,
    TaskPriority,
    WeeklyReport,
)
from common.llm.client import LLMClient
from common.models.base import BotName
from infra.config import settings

logger = logging.getLogger(__name__)

EXECUTIVE_SUMMARY_PROMPT = """
You are a senior marketing analyst for a local restaurant.
Given outputs from multiple marketing bots, write an executive summary (3-4 sentences) and generate a prioritized task list.
Respond ONLY with valid JSON:
{
  "executive_summary": "...",
  "actionable_tasks": [
    {
      "title": "Update menu page SEO",
      "description": "The SEO bot identified 3 high-priority keyword clusters...",
      "source_bot": "local_seo",
      "priority": "high",
      "tags": ["seo", "content"]
    }
  ]
}
"""

BOT_INSIGHT_PROMPT = """
You are summarizing outputs from a marketing bot for a restaurant owner.
Given the JSON output data, extract 3-5 key insights in plain English.
Respond ONLY with a JSON array of strings:
["Insight 1", "Insight 2", "Insight 3"]
"""

REPORT_TEMPLATE = """# Weekly Marketing Report — {date}

## Executive Summary
{executive_summary}

## Bot Activity Summary

{bot_summaries}

## Prioritized Action Items

{action_items}

---
*Generated by Restaurant Bots Orchestrator*
"""


class OrchestratorBot(BaseBot):
    """Synthesizes outputs from all bots into a weekly report with task list."""

    name = BotName.ORCHESTRATOR

    def __init__(
        self,
        orchestrator_input: OrchestratorInput | None = None,
        llm: LLMClient | None = None,
    ) -> None:
        super().__init__()
        self.orchestrator_input = orchestrator_input or OrchestratorInput(
            output_dir=settings.output_dir
        )
        self.llm = llm or LLMClient()
        settings.reports_dir.mkdir(parents=True, exist_ok=True)

    def run(self) -> dict:
        logger.info("OrchestratorBot: synthesizing all bot outputs")
        bot_summaries = self._collect_bot_summaries()
        synthesis = self._synthesize(bot_summaries)
        report = self._build_report(bot_summaries, synthesis)
        self._save_report(report)
        return report.model_dump(mode="json")

    def _collect_bot_summaries(self) -> list[BotSummary]:
        output_map = {
            "local_seo": "local_seo_output.json",
            "content": "content_output.json",
            "forum": "forum_review_queue.json",
            "link_building": "link_building_output.json",
            "competitor": "competitor_output.json",
            "trend_tracking": "trend_report.json",
        }
        summaries: list[BotSummary] = []
        for bot_name, filename in output_map.items():
            file_path = self.orchestrator_input.output_dir / filename
            if file_path.exists():
                try:
                    data = json.loads(file_path.read_text())
                    insights = self._extract_insights(bot_name, data)
                    summaries.append(
                        BotSummary(
                            bot_name=bot_name,
                            last_run=datetime.now(timezone.utc),
                            key_insights=insights,
                            output_files=[str(file_path)],
                        )
                    )
                except Exception as exc:
                    logger.warning("Could not process %s: %s", filename, exc)
        return summaries

    def _extract_insights(self, bot_name: str, data: dict | list) -> list[str]:
        user_prompt = f"Bot: {bot_name}\nOutput data:\n{json.dumps(data, default=str)[:3000]}"
        raw = self.llm.chat(BOT_INSIGHT_PROMPT, user_prompt, temperature=0.4)
        return json.loads(raw)

    def _synthesize(self, summaries: list[BotSummary]) -> dict:
        all_insights = {s.bot_name: s.key_insights for s in summaries}
        user_prompt = (
            f"Restaurant: {settings.restaurant_name}, {settings.restaurant_cuisine} in {settings.restaurant_city}\n"
            f"Bot insights:\n{json.dumps(all_insights, indent=2)}"
        )
        raw = self.llm.chat(EXECUTIVE_SUMMARY_PROMPT, user_prompt, temperature=0.5)
        return json.loads(raw)

    def _build_report(self, summaries: list[BotSummary], synthesis: dict) -> WeeklyReport:
        tasks = [
            ActionableTask(
                title=t["title"],
                description=t.get("description", ""),
                source_bot=t.get("source_bot", ""),
                priority=TaskPriority(t.get("priority", "medium")),
                tags=t.get("tags", []),
            )
            for t in synthesis.get("actionable_tasks", [])
        ]

        # Build markdown report
        bot_summaries_md = ""
        for s in summaries:
            bot_summaries_md += f"### {s.bot_name.replace('_', ' ').title()}\n"
            for insight in s.key_insights:
                bot_summaries_md += f"- {insight}\n"
            bot_summaries_md += "\n"

        action_items_md = ""
        for i, task in enumerate(tasks, 1):
            action_items_md += (
                f"{i}. **[{task.priority.upper()}]** {task.title}\n"
                f"   {task.description}\n\n"
            )

        report_markdown = REPORT_TEMPLATE.format(
            date=datetime.now(timezone.utc).strftime("%Y-%m-%d"),
            executive_summary=synthesis.get("executive_summary", ""),
            bot_summaries=bot_summaries_md,
            action_items=action_items_md,
        )

        return WeeklyReport(
            generated_at=datetime.now(timezone.utc),
            executive_summary=synthesis.get("executive_summary", ""),
            bot_summaries=summaries,
            actionable_tasks=tasks,
            report_markdown=report_markdown,
        )

    def _save_report(self, report: WeeklyReport) -> None:
        timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")

        json_path = settings.reports_dir / f"weekly_report_{timestamp}.json"
        json_path.write_text(report.model_dump_json(indent=2))

        md_path = settings.reports_dir / f"weekly_report_{timestamp}.md"
        md_path.write_text(report.report_markdown)

        logger.info("OrchestratorBot: saved report to %s", settings.reports_dir)
